# Generated by Django 3.2 on 2023-02-05 20:07

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default=rooms.models.EventType['PUBLIC'], max_length=10),
        ),
    ]
